# Generated by Django 5.2.6 on 2025-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id_categoria_cliente', models.AutoField(db_column='id_CATEGORIA_CLIENTE', primary_key=True, serialize=False)),
                ('nome_categoria_clientes', models.CharField(db_column='nome_CATEGORIA_CLIENTES', max_length=45)),
                ('descricao_categ_cli', models.TextField()),
            ],
            options={
                'db_table': 'categoria_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProdutos',
            fields=[
                ('id_categoria_produtos', models.AutoField(db_column='id_CATEGORIA_PRODUTOS', primary_key=True, serialize=False)),
                ('nome_categoria_produtos', models.CharField(db_column='nome_CATEGORIA_PRODUTOS', max_length=45)),
            ],
            options={
                'db_table': 'categoria_produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.AutoField(db_column='id_CLIENTES', primary_key=True, serialize=False)),
                ('senha_clientes', models.CharField(db_column='senha_CLIENTES', max_length=20)),
                ('sexo_clientes', models.CharField(db_column='sexo_CLIENTES', max_length=20)),
                ('telefone_clientes', models.CharField(db_column='telefone_CLIENTES', max_length=15)),
                ('email_clientes', models.CharField(db_column='email_CLIENTES', max_length=50)),
                ('nome_clientes', models.CharField(db_column='nome_CLIENTES', max_length=45)),
                ('sobrenome_clientes', models.CharField(db_column='sobrenome_CLIENTES', max_length=45)),
                ('cpf_clientes', models.CharField(db_column='cpf_CLIENTES', max_length=14)),
                ('status_clientes', models.IntegerField(db_column='status_CLIENTES')),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pedido', models.IntegerField(db_column='quantidade_PEDIDO')),
                ('valor_compra', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id_endereco_cliente', models.AutoField(db_column='id_ENDERECO_CLIENTE', primary_key=True, serialize=False)),
                ('cep_endereco_cliente', models.CharField(db_column='cep_ENDERECO_CLIENTE', max_length=8)),
                ('complemento_endereco_cliente', models.CharField(db_column='complemento_ENDERECO_CLIENTE', max_length=45)),
                ('bairro_endereco_cliente', models.CharField(db_column='bairro_ENDERECO_CLIENTE', max_length=45)),
                ('casa_endereco_cliente', models.CharField(db_column='casa_ENDERECO_CLIENTE', max_length=45)),
                ('rua_endereco_cliente', models.CharField(db_column='rua_ENDERECO_CLIENTE', max_length=45)),
            ],
            options={
                'db_table': 'endereco_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnderecoFuncionarios',
            fields=[
                ('id_endereco_funcionarios', models.AutoField(db_column='id_ENDERECO_FUNCIONARIOS', primary_key=True, serialize=False)),
                ('cep_endereco_funcionarios', models.CharField(db_column='cep_ENDERECO_FUNCIONARIOS', max_length=8)),
                ('complemento_endereco_funcionarios', models.CharField(db_column='complemento_ENDERECO_FUNCIONARIOS', max_length=45)),
                ('bairro_endereco_funcionarios', models.CharField(db_column='bairro_ENDERECO_FUNCIONARIOS', max_length=45)),
                ('casa_endereco_funcionarios', models.CharField(db_column='casa_ENDERECO_FUNCIONARIOS', max_length=45)),
                ('rua_endereco_funcionarios', models.CharField(db_column='rua_ENDERECO_FUNCIONARIOS', max_length=45)),
            ],
            options={
                'db_table': 'endereco_funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id_funcionarios', models.AutoField(db_column='id_FUNCIONARIOS', primary_key=True, serialize=False)),
                ('senha_funcionarios', models.CharField(db_column='senha_FUNCIONARIOS', max_length=45)),
                ('login_funcionarios', models.CharField(db_column='login_FUNCIONARIOS', max_length=45)),
                ('telefone_funcionarios', models.CharField(db_column='telefone_FUNCIONARIOS', max_length=45)),
                ('email_funcionarios', models.CharField(db_column='email_FUNCIONARIOS', max_length=45)),
                ('sexo_funcionarios', models.CharField(db_column='sexo_FUNCIONARIOS', max_length=20)),
                ('nome_funcionarios', models.CharField(db_column='nome_FUNCIONARIOS', max_length=45)),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='id_PEDIDO', primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField(db_column='data_PEDIDO')),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produtos', models.AutoField(db_column='id_PRODUTOS', primary_key=True, serialize=False)),
                ('nome_produtos', models.CharField(db_column='nome_PRODUTOS', max_length=45)),
                ('valor_produtos', models.FloatField(db_column='valor_PRODUTOS')),
                ('descricao_produtos', models.TextField(db_column='descricao_PRODUTOS')),
                ('quantidade_estoque_produtos', models.IntegerField(db_column='quantidade_estoque_PRODUTOS')),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetorFuncionarios',
            fields=[
                ('id_setor_funcionarios', models.AutoField(db_column='id_SETOR_FUNCIONARIOS', primary_key=True, serialize=False)),
                ('nome_setor_funcionarios', models.CharField(db_column='nome_SETOR_FUNCIONARIOS', max_length=45)),
                ('descricao_setor', models.TextField()),
            ],
            options={
                'db_table': 'setor_funcionarios',
                'managed': False,
            },
        ),
    ]
