# Generated by Django 5.2.6 on 2026-06-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futebol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPerfil',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'accounts_perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('opcao_resposta', models.CharField(max_length=500)),
                ('resposta_correta', models.IntegerField()),
                ('ponto', models.IntegerField()),
            ],
            options={
                'db_table': 'alternativas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoTitulos',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_titulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgressoFases',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_futebol.clientes')),
                ('fase2_liberada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'progresso_fases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id_questao', models.AutoField(primary_key=True, serialize=False)),
                ('pergunta', models.TextField()),
            ],
            options={
                'db_table': 'questoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('pk', models.CompositePrimaryKey('cliente_id', 'questao_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('combo_max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'respostas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id_titulo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_titulo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'titulos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='imagemproduto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jogos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recuperacaosenha',
            options={'managed': False},
        ),
    ]
