# Generated by Django 5.2.6 on 2025-11-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_futebol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacliente',
            options={'managed': True},
        ),
    ]
