# Generated by Django 5.2.6 on 2025-12-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futebol', '0002_alter_categoriacliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacliente',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='RecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='app_futebol.clientes')),
            ],
            options={
                'db_table': 'recuperacao_senha',
                'managed': True,
            },
        ),
    ]
