# Generated by Django 5.2.6 on 2025-12-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_futebol', '0003_alter_categoriacliente_options_recuperacaosenha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'managed': True},
        ),
    ]
