# Generated by Django 5.2.6 on 2026-01-16 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futebol', '0005_imagemproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id_jogos', models.AutoField(db_column='id_jogos', primary_key=True, serialize=False)),
                ('dia_jogo', models.DateField(db_column='dia_jogo')),
                ('hora_jogo', models.TimeField(db_column='hora_jogo')),
                ('local_jogo', models.CharField(db_column='local_jogo', max_length=50)),
                ('casa_fora', models.CharField(choices=[('casa', 'Casa'), ('fora', 'Fora')], db_column='casa_fora', max_length=4)),
            ],
            options={
                'db_table': 'jogos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id_times', models.AutoField(db_column='id_times', primary_key=True, serialize=False)),
                ('nome_time', models.CharField(db_column='nome_time', max_length=45)),
                ('url_brasao', models.CharField(blank=True, db_column='url_brasao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'times',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='produtos',
            name='categoria_produtos_id_categoria_produtos',
            field=models.ForeignKey(db_column='CATEGORIA_PRODUTOS_id_CATEGORIA_PRODUTOS', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_futebol.categoriaprodutos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='imagem_produtos',
            field=models.CharField(blank=True, db_column='imagem_PRODUTOS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='jogos_id_jogos',
            field=models.ForeignKey(blank=True, db_column='jogos_id_jogos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_futebol.jogos'),
        ),
    ]
