# Generated by Django 5.2.6 on 2026-05-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('opcao_resposta', models.CharField(max_length=500)),
                ('resposta_correta', models.IntegerField()),
                ('ponto', models.IntegerField()),
            ],
            options={
                'db_table': 'alternativas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoTitulos',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_titulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('nome_participante', models.CharField(max_length=45)),
                ('tempo', models.TimeField(blank=True, null=True)),
                ('pontuacao', models.IntegerField(blank=True, null=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'participantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id_questao', models.AutoField(primary_key=True, serialize=False)),
                ('pergunta', models.TextField()),
            ],
            options={
                'db_table': 'questoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('pk', models.CompositePrimaryKey('participante_id', 'questao_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('combo_max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'respostas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id_titulo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_titulo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'titulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgressoFases',
            fields=[
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='minigame.participantes')),
                ('fase2_liberada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'progresso_fases',
                'managed': True,
            },
        ),
    ]
