# Generated by Django 5.2.6 on 2026-05-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id_alternativa', models.IntegerField(primary_key=True, serialize=False)),
                ('opcao_resposta', models.CharField(max_length=500)),
                ('resposta_correta', models.IntegerField()),
                ('ponto', models.IntegerField()),
            ],
            options={
                'db_table': 'alternativas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('nome_participante', models.CharField(max_length=45)),
                ('tempo', models.TimeField(blank=True, null=True)),
                ('pontuacao', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'participantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id_questao', models.IntegerField(primary_key=True, serialize=False)),
                ('pergunta', models.TextField()),
            ],
            options={
                'db_table': 'questoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('pk', models.CompositePrimaryKey('participante_id', 'questao_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'respostas',
                'managed': False,
            },
        ),
    ]
