# Generated by Django 5.2.6 on 2026-06-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minigame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressofases',
            name='participante',
        ),
        migrations.DeleteModel(
            name='Alternativas',
        ),
        migrations.DeleteModel(
            name='HistoricoTitulos',
        ),
        migrations.DeleteModel(
            name='Questoes',
        ),
        migrations.DeleteModel(
            name='Respostas',
        ),
        migrations.DeleteModel(
            name='Titulos',
        ),
        migrations.DeleteModel(
            name='ProgressoFases',
        ),
        migrations.DeleteModel(
            name='Participantes',
        ),
    ]
